[package]
name = "dfr"
version = "0.0.3"
edition = "2021"
rust-version = "1.75"
description = "COMTRADE DFR 格式解析（只读）"
license = "MIT"
authors = ["sanguine (张松贵) <82018238@qq.com>"]

[dependencies]
cbase = { path = "../cbase" }
cfg = { path = "../cfg" }
dat = { path = "../dat" }

[lib]
name = "dfr"
path = "src/lib.rs"